[package]
name = "hello-triangle"
version = "0.1.0"
edition = "2018"

[dependencies]
ash = "0.33.0"
ash-window = "0.7.0"
cgmath = { version = "0.18.0", features = ["swizzle"] }
raw-window-handle = "0.3.3"
thiserror = "1.0.26"
winit = "0.25.0"

[lib]
name = "app"
path = "src/lib.rs"