[package]
name = "window-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
cgmath = { version = "0.18.0", features = ["swizzle"] }